platform :ios, '13.0'

target 'EasyTrashClub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyTrashClub
  
  pod 'Alamofire', '~> 5.2'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'

  target 'EasyTrashClubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EasyTrashClubUITests' do
    # Pods for testing
  end

end
