platform :ios, '13.0'

target 'EasyTrashClub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyTrashClub

  target 'EasyTrashClubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EasyTrashClubUITests' do
    # Pods for testing
  end

end
